version: '3.4'
services:
  postgresql:
    container_name: postgres
    image: postgres
    volumes:
        # - ./docker/pg:/var/lib/postgresql/data
        - db-main:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: CustomerMS
        PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'

  testdb:
    container_name: testdb
    image: postgres
    volumes: 
        # - ./docker/pg:/var/lib/postgresql/data
        - db-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: TestCustomerMS
        PGDATA: /var/lib/postgresql/data/pgdata2
    ports:
      - '5431:5431'
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      TZ: Asia/Tokyo
      PGADMIN_DEFAULT_EMAIL: 'naha022677@icloud.com'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'

volumes:
  db-data:
    driver: local
  db-main:
    driver: local