version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    volumes:
        # - ./docker/pg:/var/lib/postgresql/data
        - db-main:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        #POSTGRES_DB: CustomerMS
        PGDATA: /var/lib/postgresql/data/pgdata
        # POSTGRES_INITDB_ARGS: 30
    ports:
      - '5432:5432'
    extra_hosts:
        - "host.docker.internal:host-gateway"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      TZ: Asia/Tokyo
      PGADMIN_DEFAULT_EMAIL: 'naha022677@icloud.com'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'

volumes:
  db-data:
    driver: local
  db-main:
    driver: local

