import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/navigation/Sidebar";
import React from "react";
import {NextFont} from "next/dist/compiled/@next/font";

const inter: NextFont = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <div className={"wrapper"}>
            <Sidebar />
          <div className={"main-container"}>
            {/* <SearchBar /> */}
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
