version: '3.9'
services:
  nodejs:
    container_name: nodejs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/usr/src/app
    command: sh -c "cd reactpage && npm start"
    ports:
    - "3000:3000"