# OS: Debian Buster
# Node.js: 14.4.0
FROM node:18.17.1

# Create app directory
WORKDIR /usr/src/app

# # Install app dependencies (package.json and package-lock.json)
# COPY ./package.json /usr/src/app 
# RUN npm install

# # Bundle app source (server.js)
# COPY . .

# # Listen port
# EXPOSE 8080

# # Run Node.js
# CMD [ "node", "start" ]